#!/bin/bash

set -e

cd "$(dirname "$0")"
tmp=

for f in * fish/conf.d fish/functions; do
  case "$f" in
    fish|setup) continue;;
    bin) dest=~/.local/bin;;
    *) dest=~/.config/"$f";;
  esac

  if test -L "$dest"; then
    test "$(readlink "$dest")" != "$PWD/$f" || continue
  elif test -e "$dest"; then
    test -n "$tmp" || tmp="$(mktemp -dt config.XXXXXX)"

    mkdir -p "$tmp$(dirname "/$f")"
    mv "$dest" "$tmp/$f"

    echo "existing '$dest' moved to '$tmp/$f'"
  fi

  mkdir -p "$(dirname "$dest")"
  ln -snfv "$PWD/$f" "$dest"
done

touch ~/.hushlogin

if test "$(uname)" = Darwin; then
  defaults write -g ApplePressAndHoldEnabled -bool false
  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
  defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
fi
