[[language]]
name = 'git-config'
file-types = [
  { glob = '.gitmodules' },
  { glob = '.gitconfig' },
  { glob = '.git/config' },
  { glob = 'git/config' },
]

[[language]]
name = 'json'
formatter = { command = 'jq' }

[[language]]
name = 'toml'
auto-format = true
