if !has('ide')
  unlet! skip_defaults_vim
  source $VIMRUNTIME/defaults.vim

  set autoread
  set background=dark
  set colorcolumn=100
  set expandtab
  set foldlevel=99
  set foldmethod=syntax
  set hidden
  set linebreak
  set mouse=a
  set nojoinspaces
  set noswapfile
  set number
  set shiftwidth=2
  set smartindent
  set softtabstop=2
  set viminfofile=~/.local/state/viminfo

  colorscheme habamax

  let &t_SI = "\e[5 q"
  let &t_EI = "\e[2 q"

  let g:netrw_banner = 0
  let g:netrw_dirhistmax = 0
  let g:netrw_liststyle = 3
else
  set ideajoin
  set idearefactormode=visual

  source ~/.config/vim/plugin/helix-keys.vim
endif

set hlsearch
set ignorecase
set incsearch
set smartcase

nnoremap <silent> <Enter> :noh<Enter>
vnoremap <silent> <Enter> <Esc>:noh<Enter>gv
noremap :s/ :s/\v
noremap :p/ :!perl -pe 's/'<Left>

nnoremap <silent> <Space>e :Explore .<Enter>
nnoremap <silent> <Space>E :Explore<Enter>
nnoremap <silent> <Space>l :set invnumber<Enter>
nnoremap <silent> <Space>w :set invwrap<Enter>

noremap <A--> <C-w>s
noremap <A-\> <C-w>v
noremap <A-h> <C-w>h
noremap <A-j> <C-w>j
noremap <A-k> <C-w>k
noremap <A-l> <C-w>l
