unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

set autoread
set background=dark
set breakindent
set colorcolumn=+0
set completeopt=menuone,noselect
set expandtab
set hidden
set hlsearch
set ignorecase
set infercase
set linebreak
set list
set listchars=tab:»\ ,trail:·,extends:❯,precedes:❮,nbsp:␣
set mouse=a
set nojoinspaces
set number
set scrolloff=3
set shiftwidth=0
set shortmess=clTOWotFC
set smartcase
set smartindent
set tabstop=2
set viminfofile=~/.local/state/viminfo
set virtualedit=block
set whichwrap=h,l,<,>,[,]

let mapleader = "\<Space>"

noremap j gj
noremap k gk

nnoremap / :/\v
nnoremap ? ?/\v
nnoremap :s/ :s/\v
nnoremap :p/ :!perl -pe "s/"<Left>
nnoremap <silent> <Esc> :noh<Enter>
inoremap <C-k> <C-o>"_D

nnoremap <C-w>= <C-w>s
nnoremap <C-w>\ <C-w>v

nnoremap <silent> <Leader>e :Explore<Enter>
nnoremap <silent> <Leader>l :set invnumber<Enter>
nnoremap <silent> <Leader>w :set invwrap<Enter>

colorscheme habamax

let &t_SI = "\e[5 q"
let &t_EI = "\e[2 q"

let g:netrw_banner = 0
let g:netrw_dirhistmax = 0
let g:netrw_liststyle = 3
